sudo: required

language: python

python:
 - 3.6

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
 - sudo rm /usr/local/bin/docker-compose
 - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - pip install selenium
 - docker-compose build
 - docekr-compose up -d
 - ifconfig

script:
 - cd ./TestWithSelenium
 - python setup.py test

matrix:
  fast_finish: true