version: '2'

services:
  tornadoapp:
    image: matoba/tornadoapp
    ports:
      - "80:80"
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    links:
      - tornadoapp